name: "Radicale"
description: "Radicale CardDAV and CalDAV server"
version: "0.0.51"
slug: "radicale"
startup: "application"
init: false
backup: hot
hassio_api: true
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
ports:
  5232/tcp: 5232
ports_description:
  5232/tcp: "Radicale server port"
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
panel_icon: "mdi:calendar-sync"
webui: "[PROTO:ssl]://[HOST]:[PORT:5232]"
image: "ghcr.io/MathieuIci/{arch}-addon-radicale"

# Ingress will not work with Radicale as it is not built for it
# ingress: true
# ingress_port: 5232
# ingress_entry: "/"
